# Generated by Django 3.0.8 on 2020-07-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0005_details_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='color',
        ),
        migrations.RemoveField(
            model_name='details',
            name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='Delivery',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Description',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Guarantee',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Warranty',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image1',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='offers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Desktops', 'Desktops'), ('Printers', 'Printers'), ('Survilliance', 'Survilliance'), ('LED TV', 'LED TV'), ('Tablets', 'Tablets'), ('Biometrics', 'Biometrice'), ('UPS', 'UPS'), ('Cables', 'Cables'), ('Accessories', 'Accessories')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
