# Generated by Django 3.0.8 on 2020-07-14 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0006_auto_20200714_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Guarantee',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image2',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='media/')),
                ('img2', models.ImageField(null=True, upload_to='media/')),
                ('img3', models.ImageField(null=True, upload_to='media/')),
                ('img4', models.ImageField(null=True, upload_to='media/')),
                ('img5', models.ImageField(null=True, upload_to='media/')),
                ('idi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='second.Products')),
            ],
        ),
    ]
