# Generated by Django 3.0.8 on 2020-07-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0007_auto_20200714_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Color',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='FAQ',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='StockLeft',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
