# Generated by Django 3.0.8 on 2020-07-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0008_auto_20200714_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='More_Info',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Specifications',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
