# Generated by Django 3.0.8 on 2020-07-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0009_auto_20200714_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='FAQ',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='More_Info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Specifications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='offers',
            field=models.TextField(null=True),
        ),
    ]
