# Generated by Django 3.0.8 on 2020-07-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0010_auto_20200719_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
